@extends('layouts.admin')
@section('title', 'الأطباء')
@section('page-title', 'الأطباء')
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">لوحة التحكم</a></li>
    <li class="breadcrumb-item active">الأطباء</li>
@endsection
@section('page-actions')
    <a href="{{ route('admin.doctors.create') }}" class="btn btn-primary"><i class="fas fa-plus me-2"></i>إضافة طبيب</a>
@endsection
@section('content')
<div class="card mb-3"><div class="card-body py-2"><form method="GET" class="row g-2 align-items-end"><div class="col-md-4"><input type="text" name="search" class="form-control form-control-sm" placeholder="البحث عن أطباء..." value="{{ request('search') }}"></div><div class="col-md-3"><select name="department_id" class="form-select form-select-sm"><option value="">جميع الأقسام</option>@foreach($departments as $dept)<option value="{{ $dept->id }}" {{ request('department_id') == $dept->id ? 'selected' : '' }}>{{ $dept->name }}</option>@endforeach</select></div><div class="col-md-2"><select name="is_available" class="form-select form-select-sm"><option value="">جميع</option><option value="1" {{ request('is_available') === '1' ? 'selected' : '' }}>متاح</option><option value="0" {{ request('is_available') === '0' ? 'selected' : '' }}>غير متاح</option></select></div><div class="col-md-3"><button type="submit" class="btn btn-primary btn-sm me-1"><i class="fas fa-search"></i> تصفية</button><a href="{{ route('admin.doctors.index') }}" class="btn btn-secondary btn-sm">إعادة تعيين</a></div></form></div></div>
<div class="card"><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover mb-0"><thead class="table-light"><tr><th>#</th><th>الطبيب</th><th>التخصص</th><th>القسم</th><th>الخبرة</th><th>الرسوم</th><th>الحالة</th><th>الإجراءات</th></tr></thead><tbody>@forelse($doctors as $doctor)<tr><td>{{ $doctors->firstItem() + $loop->index }}</td><td><div class="d-flex align-items-center"><div class="bg-info bg-opacity-10 text-info rounded-circle d-flex align-items-center justify-content-center me-2" style="width:36px;height:36px;font-size:0.8rem;font-weight:700;flex-shrink:0;">{{ strtoupper(substr($doctor->user->name ?? 'DR', 0, 2)) }}</div><div><div class="fw-semibold">{{ $doctor->user->name ?? 'N/A' }}</div><small class="text-muted">{{ $doctor->user->email ?? '' }}</small></div></div></td><td><span class="badge bg-primary bg-opacity-10 text-primary">{{ $doctor->specialization }}</span></td><td>{{ $doctor->department->name ?? '-' }}</td><td>{{ $doctor->experience_years }} سنوات</td><td>${{ number_format($doctor->consultation_fee, 2) }}</td><td>@if($doctor->is_available)<span class="badge bg-success">متاح</span>@else<span class="badge bg-secondary">غير متاح</span>@endif</td><td><div class="btn-group btn-group-sm"><a href="{{ route('admin.doctors.show', $doctor) }}" class="btn btn-outline-info" title="عرض"><i class="fas fa-eye"></i></a><a href="{{ route('admin.doctors.edit', $doctor) }}" class="btn btn-outline-primary" title="تعديل"><i class="fas fa-edit"></i></a><form action="{{ route('admin.doctors.destroy', $doctor) }}" method="POST" class="d-inline" onsubmit="return confirm('هل تريد حذف هذا الطبيب؟')">@csrf @method('DELETE')<button type="submit" class="btn btn-outline-danger" title="حذف"><i class="fas fa-trash"></i></button></form></div></td></tr>@empty<tr><td colspan="8" class="text-center text-muted py-5"><i class="fas fa-user-md fa-2x mb-2 d-block opacity-25"></i>لا يوجد أطباء. <a href="{{ route('admin.doctors.create') }}">إضافة أول طبيب</a></td></tr>@endforelse</tbody></table></div></div>@if($doctors->hasPages())<div class="card-footer">{{ $doctors->appends(request()->query())->links() }}</div>@endif</div>
@endsection
