@extends('layouts.admin')
@section('title', 'الفواتير')
@section('page-title', 'الفواتير')
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">لوحة التحكم</a></li>
    <li class="breadcrumb-item active">الفواتير</li>
@endsection
@section('page-actions')
    <a href="{{ route('admin.invoices.create') }}" class="btn btn-primary"><i class="fas fa-plus me-2"></i>إنشاء فاتورة</a>
@endsection
@section('content')
<div class="card mb-3"><div class="card-body py-2"><form method="GET" class="row g-2 align-items-end"><div class="col-md-4"><input type="text" name="search" class="form-control form-control-sm" placeholder="البحث عن مريض أو رقم فاتورة..." value="{{ request('search') }}"></div><div class="col-md-2"><select name="status" class="form-select form-select-sm"><option value="">جميع الحالات</option><option value="unpaid" {{ request('status') == 'unpaid' ? 'selected' : '' }}>غير مدفوعة</option><option value="paid" {{ request('status') == 'paid' ? 'selected' : '' }}>مدفوعة</option><option value="partial" {{ request('status') == 'partial' ? 'selected' : '' }}>جزئي</option><option value="cancelled" {{ request('status') == 'cancelled' ? 'selected' : '' }}>ملغاة</option></select></div><div class="col-md-2"><input type="date" name="date_from" class="form-control form-control-sm" value="{{ request('date_from') }}"></div><div class="col-md-1"><input type="date" name="date_to" class="form-control form-control-sm" value="{{ request('date_to') }}"></div><div class="col-md-3"><button type="submit" class="btn btn-primary btn-sm me-1"><i class="fas fa-search"></i> تصفية</button><a href="{{ route('admin.invoices.index') }}" class="btn btn-secondary btn-sm">إعادة تعيين</a></div></form></div></div>
<div class="card"><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover mb-0"><thead class="table-light"><tr><th>رقم الفاتورة</th><th>المريض</th><th>الطبيب</th><th>التاريخ</th><th>المبلغ</th><th>الحالة</th><th>الإجراءات</th></tr></thead><tbody>@forelse($invoices as $invoice)<tr><td><span class="fw-semibold">{{ $invoice->invoice_number }}</span></td><td><div class="fw-semibold">{{ $invoice->patient->name ?? 'N/A' }}</div></td><td><small>{{ $invoice->doctor->user->name ?? '-' }}</small></td><td><small>{{ $invoice->invoice_date->format('M d, Y') }}</small></td><td><strong>${{ number_format($invoice->total_amount, 2) }}</strong></td><td>@php $colors=['unpaid'=>'warning','paid'=>'success','partial'=>'info','cancelled'=>'danger']; @endphp<span class="badge bg-{{ $colors[$invoice->status] ?? 'secondary' }}">{{ ucfirst($invoice->status) }}</span></td><td><div class="btn-group btn-group-sm"><a href="{{ route('admin.invoices.show', $invoice) }}" class="btn btn-outline-info" title="عرض"><i class="fas fa-eye"></i></a><a href="{{ route('admin.invoices.edit', $invoice) }}" class="btn btn-outline-primary" title="تعديل"><i class="fas fa-edit"></i></a><a href="{{ route('admin.invoices.print', $invoice) }}" class="btn btn-outline-secondary" title="طباعة" target="_blank"><i class="fas fa-print"></i></a></div></td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-5"><i class="fas fa-file-invoice-dollar fa-2x mb-2 d-block opacity-25"></i>لا توجد فواتير.</td></tr>@endforelse</tbody></table></div></div>@if($invoices->hasPages())<div class="card-footer">{{ $invoices->appends(request()->query())->links() }}</div>@endif</div>
@endsection
